export default {
  spaceGroteskBold: "SpaceGrotesk-Bold",
  spaceGroteskLight: "SpaceGrotesk-Light",
  spaceGroteskMedium: "SpaceGrotesk-Medium",
  spaceGroteskRegular: "SpaceGrotesk-Regular",
  spaceGroteskSemiBold: "SpaceGrotesk-SemiBold",
  DMSansBold: 'DMSans-Bold',
  DMSansLight: 'DMSans-Light',
  DMSansMedium: 'DMSans-Medium',
  DMSansRegular: 'DMSans-regular',
  DMSansSemiBold: 'DMSans-SemiBold',
  poppinsBlack: "Poppins-Black",
  poppinsBold: "Poppins-Bold",
  poppinsExtraBold: "Poppins-ExtraBold",
  poppinsExtraLight: "Poppins-ExtraLight",
  poppinsLight: "Poppins-Light",
  poppinsMedium: "Poppins-Medium",
  poppinsRegular: "Poppins-Regular",
  poppinsSemiBold: "Poppins-SemiBold",
  poppinsThin: "Poppins-Thin",
};
